### PR TITLE
DB Query Logic Changes, Cleanup, Static File, Logging

### PR DESCRIPTION
**Pull request by JasonLing95**
# Updates
- Change logging to one handler which output to two files (error and debug)
- Some uppercase and width addition in `form.py`
- Loading locally static files in `base.html` - Bootstrap5, DataTables, jQuery, CSS
- Delete `monthly_compute.html` - making a single `compute.html` which replace both `daily_compute.html` and `monthly_compute.html`
- Cleanup all html files to have the same visual format
- added `constants.py` for plot configuration used across different .py files
- changes to some db query logic 

Ploutos (this PR: image name ploutos_web v1.0-a) is currently deployed on dev server

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/39)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 41 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/39)* status: 41 of 47 files reviewed, 7 unresolved discussions (waiting on @JasonLing95 and @Yu-jinKim)

___
*[`Ploutos/scripts/constants.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOb6pV-TFhd-TrAGZt:-NOOb6pV-TFhd-TrAGZu:btijkyw) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/constants.py#L1)):*
> ```Python
> MONTHS = {
> ```

could this have a docstring at the top to explain everything in here and maybe some comments for each for future us
___
*[`Ploutos/scripts/executions_plots.py` line 370 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOcNi3-OQsKVUH0ztI:-NOOcNi3-OQsKVUH0ztJ:b-ty3iwe) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L370)):*
> ```Python
>                                 )
> 
>                 q = [(int(
> ```

comment for this pls
___
*[`Ploutos/scripts/executions_plots.py` line 529 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOcX6YC8YzQHes9qYi:-NOOcX6YC8YzQHes9qYj:b-f01jd5) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L529)):*
> ```Python
>                     )
> 
>                     if e['total_cost'] is None:
> ```

`if not e['total_cost']:`

also single char variables make this harder to read



_Code quote:_
```Python
if e['total_cost'] is None:
```
___
*[`Ploutos/scripts/executions_plots.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOckREB9u8rB6Kmu7G:-NOOckREB9u8rB6Kmu7H:b-g1kmmr) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L574)):*
> ```Python
>             'form': the form to pass to HTML
>         """
>         q = ComputeCosts.objects.values('date__date').annotate(
> ```

again single char variables are harder to read, what is `q`  here?



_Code quote:_
```Python
        q = ComputeCosts.objects.values('date__date').annotate(
            Sum('total_cost')).values_list('date__date', 'total_cost__sum')

        q = [(int(










            datetime.combine(d, datetime.min.time()).strftime('%s'))
            * 1000, cost) for d, cost in q]
```
___
*[`Ploutos/scripts/executions_plots.py` line 660 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOctClDsuVjR0lRgnz:-NOOctClDsuVjR0lRgo-:b-jqsva1) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L660)):*
> ```Python
> 
>             f = q.filter(
>                 date__date__month=current_month.month,
> ```

can we switch the single chars please



_Code quote:_
```Python
            k = '{} {}'.format(
                    MONTHS[current_month.month],
                    current_month.year
                )

            f = q.filter(
                date__date__month=current_month.month,
                date__date__year=current_month.year)
            if f:
                total_cost = f[0]['total_cost']
```
___
*[`Ploutos/scripts/file_plots.py` line 227 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOd5IL0bZOI92h6AOr:-NOOd5IL0bZOI92h6AOs:b2ni0ya) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L227)):*
> ```Python
>         category_data_source = []
> 
>         if date_to_filter is None:
> ```

daT



_Code quote:_
```Python
if date_to_filter is None:
```
___
*[`Ploutos/scripts/file_plots.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOdABYCL5rWNpm3XMg:-NOOdABZC_vjMshhdLpN:bf3yikm) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L511)):*
> ```Python
>         category_data_source = []
> 
>         if date_to_filter is None:
> ```

`if not date_to_filter:`



_Code quote:_
```Python
if date_to_filter is None:
```

**Review by Yu-jinKim — CHANGES_REQUESTED** [review]
> Reviewed 6 of 47 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/39)* status: all files reviewed, 19 unresolved discussions (waiting on @JasonLing95)

___
*[`Ploutos/scripts/executions_plots.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP4IvlBrP9VbShSg-l:-NOP4IvlBrP9VbShSg-m:b-6uwd4i) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L27)):*
> ```Python
> import pandas as pd
> 
> from typing import Union
> ```

already imported above
___
*[`Ploutos/scripts/executions_plots.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP4cLT8-d0Ym8pXJl3:-NOP4cLT8-d0Ym8pXJl4:b9mxyu8) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L164)):*
> ```Python
>         }
> 
>     def str_to_list(self, string: str) -> list:
> ```

i'm questioning the need for this function since the line is already a one liner
___
*[`Ploutos/scripts/executions_plots.py` line 305 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP4t3FE97QhLEMgxq_:-NOP4t3FE97QhLEMgxqa:b-aiwkgy) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L305)):*
> ```Python
> 
>         converted_months = [
>             '{} {}'.format(self.months_in_year[m], y) for m, y in months]
> ```

no f-strings?
___
*[`Ploutos/scripts/executions_plots.py` line 400 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP55U-3Jve-MImWx1M:-NOP55U-3Jve-MImWx1N:bovrgyv) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L400)):*
> ```Python
>                     }
> 
>                 series_data.append(compute_data)
> ```

could you add a blank line here to separate this block with the lines under?
___
*[`Ploutos/scripts/executions_plots.py` line 419 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5QLc2KybkdKOF2Tn:-NOP5QLc2KybkdKOF2To:bzd24k5) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L419)):*
> ```Python
>         return json_chart_data, chart_html
> 
>     def monthly_filterby(
> ```

could we get a bit more comments in this function?
___
*[`Ploutos/scripts/executions_plots.py` line 589 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5aDA4rCZHg6GiW-X:-NOP5aDA4rCZHg6GiW-Y:b5lxj9q) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L589)):*
> ```Python
>         xaxis = [unix for unix, _ in q]
> 
>         # series_data_source.append(compute_data)
> ```

delete plz
___
*[`Ploutos/scripts/executions_plots.py` line 654 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5gkT3n3P-VWyCgYI:-NOP5gkT3n3P-VWyCgYJ:b-giyd8y) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L654)):*
> ```Python
>             xaxis.add(current_month)
> 
>             k = '{} {}'.format(
> ```

i like f-strings
___
*[`Ploutos/scripts/executions_plots.py` line 672 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5mrT-k8cf0-uG9Uy:-NOP5mrUBfTgnmGQ4tl-:b5lxj9q) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L672)):*
> ```Python
>         xaxis = [d.strftime('%b %Y') for d in sorted(xaxis)]
> 
>         # category_data_source.append(new_dict)
> ```

delete plz
___
*[`Ploutos/scripts/executions_plots.py` line 685 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5uIF0Poe1FSVEy_4:-NOP5uIF0Poe1FSVEy_5:b-j311us) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L685)):*
> ```Python
>         return json_chart_data
> 
>     def convert_to_df_alldata(
> ```

could use some comments in this function
___
*[`Ploutos/scripts/file_plots.py` line 597 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP6QFo05G8NW4N89dt:-NOP6QFo05G8NW4N89du:b-pb825d) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L597)):*
> ```Python
>         for count, item in enumerate(queue):
>             if assay:
>                 # assay filter
> ```

a bit more detail plz + looks like you're annotating as well
___
*[`Ploutos/scripts/file_plots.py` line 608 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP6Z7Q8_dU9wwfepjW:-NOP6Z7Q8_dU9wwfepjX:b-99plhg) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L608)):*
> ```Python
>                 )
>             else:
>                 # project filter
> ```

more details
___
*[`Ploutos/scripts/leaderboard_plots.py` line 1165 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP7BiU8iaxQ-pAgAwZ:-NOP7BiU8iaxQ-pAgAw_:bf2mjko) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/leaderboard_plots.py#L1165)):*
> ```Python
>         xaxis = set()
> 
>         for user in users:
> ```

comment plz

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/39)* status: 36 of 59 files reviewed, 19 unresolved discussions (waiting on @JasonLing95, @jethror1, and @Yu-jinKim)

___
*[`Ploutos/scripts/constants.py` line 1 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOb6pV-TFhd-TrAGZt:-NOPelEgD30tN4-rmFUz:bnxhvec) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/constants.py#L1)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

could this have a docstring at the top to explain everything in here and maybe some comments for each for future us
</blockquote></details>

added docstring to the file
___
*[`Ploutos/scripts/executions_plots.py` line 27 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP4IvlBrP9VbShSg-l:-NOPenqE6Kg7QgN6HRgF:b-7ql1td) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L27)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

already imported above
</blockquote></details>

fixed
___
*[`Ploutos/scripts/executions_plots.py` line 164 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP4cLT8-d0Ym8pXJl3:-NOUNHCZ21zj4EnTP1gH:bbu7gv1) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L164)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i'm questioning the need for this function since the line is already a one liner
</blockquote></details>

function removed
___
*[`Ploutos/scripts/executions_plots.py` line 305 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP4t3FE97QhLEMgxq_:-NOUO1zwBPubf03eRH8x:by8qd30) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L305)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

no f-strings?
</blockquote></details>

f-stringed
___
*[`Ploutos/scripts/executions_plots.py` line 370 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOcNi3-OQsKVUH0ztI:-NOUXR6s6JqLb2LYyMSV:b51kggp) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L370)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

comment for this pls
</blockquote></details>

added comments
___
*[`Ploutos/scripts/executions_plots.py` line 400 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP55U-3Jve-MImWx1M:-NOUXTpo9cJuEnEOHlPh:bjy6ie1) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L400)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

could you add a blank line here to separate this block with the lines under?
</blockquote></details>

line added
___
*[`Ploutos/scripts/executions_plots.py` line 419 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5QLc2KybkdKOF2Tn:-NOUck6T7SpgdU1pBDhi:b-p1i752) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L419)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

could we get a bit more comments in this function?
</blockquote></details>

added comment
___
*[`Ploutos/scripts/executions_plots.py` line 529 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOcX6YC8YzQHes9qYi:-NOUafRE18ew5KMxche_:b-7ql1td) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L529)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if not e['total_cost']:`

also single char variables make this harder to read
</blockquote></details>

fixed
___
*[`Ploutos/scripts/executions_plots.py` line 574 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOckREB9u8rB6Kmu7G:-NOUaiZw05vKDA9x9Sci:b-7ql1td) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L574)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

again single char variables are harder to read, what is `q`  here?
</blockquote></details>

fixed
___
*[`Ploutos/scripts/executions_plots.py` line 589 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5aDA4rCZHg6GiW-X:-NOUbDn-EGm88NmaNJUj:b-9unw5o) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L589)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

delete plz
</blockquote></details>

deleted
___
*[`Ploutos/scripts/executions_plots.py` line 654 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5gkT3n3P-VWyCgYI:-NOUcm5HDG6isD2-XB9m:by8qd30) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L654)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

i like f-strings
</blockquote></details>

f-stringed
___
*[`Ploutos/scripts/executions_plots.py` line 660 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOctClDsuVjR0lRgnz:-NOUbz1FBJHD3g2vOpIu:b-n9tkhd) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L660)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can we switch the single chars please
</blockquote></details>

changed
___
*[`Ploutos/scripts/executions_plots.py` line 672 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5mrT-k8cf0-uG9Uy:-NOUc-IqE6sld4RHeDW-:b-9unw5o) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L672)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

delete plz
</blockquote></details>

deleted
___
*[`Ploutos/scripts/executions_plots.py` line 685 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP5uIF0Poe1FSVEy_4:-NOUcX9-EmL3Q2866Qq9:bmg5256) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/executions_plots.py#L685)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

could use some comments in this function
</blockquote></details>

added more comments
___
*[`Ploutos/scripts/file_plots.py` line 227 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOd5IL0bZOI92h6AOr:-NOUc_Ks5I8_v6S9WWHE:b-evzzu1) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L227)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

daT
</blockquote></details>

changed to if `not date_to_filter`
___
*[`Ploutos/scripts/file_plots.py` line 511 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOOdABYCL5rWNpm3XMg:-NOU4ld33-YhfncJir0w:b-n9tkhd) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L511)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if not date_to_filter:`
</blockquote></details>

changed
___
*[`Ploutos/scripts/file_plots.py` line 597 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP6QFo05G8NW4N89dt:-NOUBznF1sK6y1fvtPbF:b-6fip) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L597)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

a bit more detail plz + looks like you're annotating as well
</blockquote></details>

added some comment below function
___
*[`Ploutos/scripts/file_plots.py` line 608 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP6Z7Q8_dU9wwfepjW:-NOUBxTU1_GurlMGJPoX:b-6fip) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/file_plots.py#L608)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

more details
</blockquote></details>

added some comment below function

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/39)* status: 36 of 59 files reviewed, 19 unresolved discussions (waiting on @jethror1 and @Yu-jinKim)

___
*[`Ploutos/scripts/leaderboard_plots.py` line 1165 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/39#-NOP7BiU8iaxQ-pAgAwZ:-NOUd6S03p6CcS_Low2q:bvsqwnt) ([raw file](https://github.com/eastgenomics/Ploutos/blob/5692bcf89c4a627647053d82a9904e65a101fce6/Ploutos/scripts/leaderboard_plots.py#L1165)):*
<details><summary><i>Previously, Yu-jinKim wrote…</i></summary><blockquote>

comment plz
</blockquote></details>

commented

**Review by jethror1 — APPROVED** [review]
> Reviewed 21 of 23 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/39)* status: 58 of 59 files reviewed, 15 unresolved discussions (waiting on @Yu-jinKim)

**Review by Yu-jinKim — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/39)* status: 58 of 59 files reviewed, 3 unresolved discussions (waiting on @jethror1)

**Pull request merged**
