### PR TITLE
Small fix to the right query data for compute querying

### PR DESCRIPTION
**Pull request by RSWilson1**
- Small fix to the right query data for compute querying, the variables in question are midnight_1day_ago and midnight_2_days_ago which were set to 14 and 15 for testing instead of 1 and 2.

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/25)

### CODE REVIEW

**Comment by RSWilson1** [comment]
Added a fix for issue https://github.com/eastgenomics/Ploutos/issues/22.

**Comment by RSWilson1** [comment]
Added fix for issue https://github.com/eastgenomics/Ploutos/issues/21.

**Comment by RSWilson1** [comment]
All fixes done for this pull request now.

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/25)* status: 2 of 3 files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

___
*[`Ploutos/dashboard/views.py` line 646 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/25#-NGSEnHHA10lxlXHfex2:-NGSEnHIDfXo1oGeHa8_:byewd67) ([raw file](https://github.com/eastgenomics/ploutos/blob/d295d4645e24b5b6c10828427cc9f1eb382fc928/Ploutos/dashboard/views.py#L646)):*
> ```Python
>             form
>         )
>         print(context)
> ```

can you remove the added prints please



_Code quote:_
```Python
print(context)
```

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/25)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
