### PR TITLE
Analyses queries

### PR DESCRIPTION
**Pull request by RSWilson1**
- Added queries to get API data for executions.
- Added function to calculate runtime - still testing as it sometimes disagrees with dx describe.
- Added functionality to deal with jobs/analyses in progress at time of running.
- Added function to add data to database.

I have attached images of the database tables.

image
image
image
image

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6)* status: 0 of 3 files reviewed, 17 unresolved discussions (waiting on @rklocke and @RSWilson1)

___
*[`Ploutos/scripts/DNAnexus_queries.py` line 76 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iusdb16hkF55PAU1N:-N5iusdb16hkF55PAU1O:bbsl80p) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L76)):*
> ```Python
> 
> 
> def setup_logging():
> ```

here's an example of setting up loggers which might be useful:

set up: https://github.com/eastgenomics/Genetics_Ark/blob/44567a3710ef55bbd156f967715bcf0e0ba4e60f/ga_core/settings.py#L217

using: https://github.com/eastgenomics/Genetics_Ark/blob/44567a3710ef55bbd156f967715bcf0e0ba4e60f/DNAnexus_to_igv/find_dx_data.py#L366
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 709 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ivzzZEsL6gMMGDDlb:-N5ivzz_5GMfT8QT_je5:byxjrxj) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L709)):*
> ```Python
> 
>     check = peek(executions)
>     if check is None:
> ```

generally more pythonic to write as `if not check:` to check for falseness, opposite for truth is `if check:`
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 716 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iwS004b9d5pKxnc4_:-N5iwS004b9d5pKxnc4a:b-z4swvx) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L716)):*
> ```Python
>         project_executions_dict = defaultdict(lambda: {"executions": []})
>         for job in executions:
>             if job['describe']['state'] == "in_progress"\
> ```

a nicer way sometimes of formatting things like this that get too long is like:

```
if (
    job['describe']['state'] == "in_progress" or
    job['describe']['state'] == "terminating"
):
    logger.log(f"{job['describe']['id']}")
```

using parentheses means you don't need `\` and indentation warnings should be taken care of, I also find it easier to read having the logical statements stacked like that
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 720 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ix9TQ4r8x5_jRjWer:-N5ix9TQ4r8x5_jRjWes:b-lkg225) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L720)):*
> ```Python
>                 logger.log(f"{job['describe']['id']}")
>             else:
>                 type = str(job['id'])
> ```

will `job['id']` not always be a string?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 721 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ixIro9pyKqKnpvmx4:-N5ixIro9pyKqKnpvmx5:beh06et) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L721)):*
> ```Python
>             else:
>                 type = str(job['id'])
>                 if type[0] == "j":
> ```

this is fine but not as clear as something like 

```
if job['id'].startswith('job-'):
    # it's a single job
    .....
elif job['id'].startswith('analysis-'):
    # its a workflow(?)
    .....
else:
    # something wrong
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 743 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ixx2z0LuzVDArRC1B:-N5ixx2z0LuzVDArRC1C:bdsh5p2) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L743)):*
> ```Python
>                         "job_name": job['describe']['name'],
>                         "executable_name": job['describe']['executableName'],
>                         "cost": job['describe']['totalPrice'],
> ```

does this totalPrice match the browser / dx describe?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 832 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iy6jR16aFljZlYTFd:-N5iy6jR16aFljZlYTFe:b-c69lvq) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L832)):*
> ```Python
>         # Once all project executions are retrieved, append the final dict
>         for future in concurrent.futures.as_completed(futures):
>             if future.result() is None:
> ```

`if not future.result():`
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 913 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iyD1t3oMhgOF9XdGr:-N5iyD1t3oMhgOF9XdGs:bpzbf83) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L913)):*
> ```Python
>         try:
>             keys = [key for key in execution.keys()]
>             print("---")
> ```

is this just for testing? if it's staying you can write it as `print(f'---\n{keys}\n---')`
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 920 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iyeM04Hpwe_8ZJZMI:-N5iyeM04Hpwe_8ZJZMJ:bkecfaj) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L920)):*
> ```Python
>             subjobs_list = []
>         except IndexError as e:
>             print(f"No key present, see error: {e}. Skipped")
> ```

Instead of this I'd check for the keys list after doing your comp, if it is empty you can continue

```
if not keys:
    # empty list => no keys
    continue
else:
    # found some keys
    ...
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 958 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5izOJ88cfrpFoxoS_K:-N5izOJ88cfrpFoxoS_L:bo4lc2c) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L958)):*
> ```Python
>                     origin_job=str(entry['id']),
>                     describe=True,
>                     first_page_size=200,
> ```

 what does `first_page_size` do? does it return the response in a list of dicts vs one big one?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 988 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5izt6REBd_DbEZ95il:-N5izt6S05Ze7bKKbD5o:bexhcei) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L988)):*
> ```Python
>     df = make_executions_subjobs_df(project_executions_dict)
>     result = []
>     for index, row in df.iterrows():
> ```

generally if you end up iterating on a df there is a better / more efficient way to do it as iterating is pretty slow, something like this would be better:

```
df["Result"] = df['Executions'].apply(
    lambda x: sum([int(value['describe']['runtime']) for value in x])
)
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1030 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j0TezBMbvHZ4Ol0cO:-N5j0TezBMbvHZ4Ol0cP:b-ny8euw) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L1030)):*
as before, please be explicit and use `.startswith()`, another advantage is it can handle empty strings:

```
>>> s=''
>>> s.startswith('job-')
False
>>> s[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: string index out of range
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1085 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j0z2oDe7Id3tQ6lSH:-N5j0z2oDe7Id3tQ6lSI:b-58so6z) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L1085)):*
> ```Python
> 
> def peek(iterable):
>     """peek
> ```

needed?



_Code quote:_
```Python
peek
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1092 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j1LC4CdAkw4LihspL:-N5j1LC4CdAkw4LihspM:b-9tmeh4) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L1092)):*
> ```Python
> 
>     Returns:
>         _type_: _description_
> ```

these autogenerated and not filled?

also, are you using the returned output? if you're just using it for truth I'd return True / False 



_Code quote:_
```Python
peek
```
___
*[`Ploutos/scripts/populate_db.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j-vgE9jMs_7zDZM1J:-N5j-vgE9jMs_7zDZM1K:b-wgnw40) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/populate_db.py#L5)):*
> ```Python
> """
> import datetime as dt
> from http.server import executable
> ```

guessing this isn't intentional import?
___
*[`Ploutos/scripts/populate_db.py` line 128 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j3-h99BS3Dy15vOt_:-N5j3-h99BS3Dy15vOta:b-ktibzj) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/populate_db.py#L128)):*
> ```Python
>     """
> 
>     today_date = queries.no_of_days_in_month()[0]
> ```

this returns 2 objects, specifying one returns in a tuple. It would be better to reference both:

```
today_date, day_count = queries.no_of_days_in_month()
```

if you don't need a variable that is returned it is standard to do this to signify it isn't used:

```
today_date, _ = queries.no_of_days_in_month()
```
___
*[`Ploutos/scripts/populate_db.py` line 155 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j3ZNi-Lc0fhjpe_PC:-N5j3ZNi-Lc0fhjpe_PD:b-w987u1) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/populate_db.py#L155)):*
> ```Python
>     It then populates the database with this data.
> 
>     --- This is still in development with the models.py ---
> ```

will come back to this in next PR

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6)* status: 1 of 4 files reviewed, 17 unresolved discussions (waiting on @rklocke and @RSWilson1)

**Review by RSWilson1 — COMMENTED** [review]
Reduced PEP8 violations, mostly a few line lengths which I think are okay? The Populate_db.py line length violation is quite bad is it possible to split that line and any best practices when imports go over line limit?

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6#-:-N68fwdr3uG_TmiiZ7gA:bss7scp)* status: 0 of 4 files reviewed, 18 unresolved discussions (waiting on @jethror1 and @rklocke)

___
*[`Ploutos/dashboard/models.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N67g2g3Aa_7iVIhIpuk:-N67g2g3Aa_7iVIhIpul:b-6h3bcm) ([raw file](https://github.com/eastgenomics/ploutos/blob/d537c2ef6d30ff2cc6bda7dffafdb78ebff8e78b/Ploutos/dashboard/models.py#L32)):*
> ```Python
> class DailyOrgRunningTotal(models.Model):
>     """Model representing running totals for the org"""
>     date = models.ForeignKey(Dates, on_delete=models.CASCADE, unique=True)
> ```

This line gives an error when run with django (see snippet), should we change this to a OnetoOneField?



_Code snippet:_
```Python
dashboard.DailyOrgRunningTotal.date: (fields.W342) Setting unique=True on a ForeignKey has the same effect as using a OneToOneField.
        HINT: ForeignKey(unique=True) is usually better served by a OneToOneField.
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 76 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iusdb16hkF55PAU1N:-N67K6tv7LewNZOKR90n:b-5budf8) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L76)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

here's an example of setting up loggers which might be useful:

set up: https://github.com/eastgenomics/Genetics_Ark/blob/44567a3710ef55bbd156f967715bcf0e0ba4e60f/ga_core/settings.py#L217

using: https://github.com/eastgenomics/Genetics_Ark/blob/44567a3710ef55bbd156f967715bcf0e0ba4e60f/DNAnexus_to_igv/find_dx_data.py#L366
</blockquote></details>

I changed the logging to the genetics_ark style.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 709 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ivzzZEsL6gMMGDDlb:-N68bd_A73i5K_DynZfB:b-n7astd) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L709)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

generally more pythonic to write as `if not check:` to check for falseness, opposite for truth is `if check:`
</blockquote></details>

Yep, I'll go with this.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 716 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iwS004b9d5pKxnc4_:-N68bikf1w0e1p4X3CFs:bmaj34f) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L716)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

a nicer way sometimes of formatting things like this that get too long is like:

```
if (
    job['describe']['state'] == "in_progress" or
    job['describe']['state'] == "terminating"
):
    logger.log(f"{job['describe']['id']}")
```

using parentheses means you don't need `\` and indentation warnings should be taken care of, I also find it easier to read having the logical statements stacked like that
</blockquote></details>

Yep changed to this formatting
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 720 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ix9TQ4r8x5_jRjWer:-N67KFvx1OQgKlJibw1G:b2nhswv) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L720)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will `job['id']` not always be a string?
</blockquote></details>

Yep
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 721 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ixIro9pyKqKnpvmx4:-N67MYFI-s164Lz9qYca:b7a6yr7) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L721)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this is fine but not as clear as something like 

```
if job['id'].startswith('job-'):
    # it's a single job
    .....
elif job['id'].startswith('analysis-'):
    # its a workflow(?)
    .....
else:
    # something wrong
```
</blockquote></details>

This looks much better! Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 743 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5ixx2z0LuzVDArRC1B:-N67MajV-4SzwS8ixSHV:b-dfn3wj) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L743)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

does this totalPrice match the browser / dx describe?
</blockquote></details>

Yes, I checked it matches, it works with just a small difference in browser and describe rounding the totalPrice.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 832 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iy6jR16aFljZlYTFd:-N67Naj-8MCiv8Jfq7pI:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L832)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

`if not future.result():`
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 913 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iyD1t3oMhgOF9XdGr:-N5oflXbAQQ2AHUu5blP:b-rz1437) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L913)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this just for testing? if it's staying you can write it as `print(f'---\n{keys}\n---')`
</blockquote></details>

Just testing, removed now.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 920 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5iyeM04Hpwe_8ZJZMI:-N67Nd9P73iJJUHK2z05:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L920)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

Instead of this I'd check for the keys list after doing your comp, if it is empty you can continue

```
if not keys:
    # empty list => no keys
    continue
else:
    # found some keys
    ...
```
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 958 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5izOJ88cfrpFoxoS_K:-N5ofpld5FND7p3L45qS:bmvhd7a) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L958)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

 what does `first_page_size` do? does it return the response in a list of dicts vs one big one?
</blockquote></details>

My understanding is the default is 100 and always passed and that's just how DNAnexus passes results, so I increased the default limit. I have removed it for now.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 988 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5izt6REBd_DbEZ95il:-N67NfyG94gGY8_vEy-6:bxx74lf) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L988)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

generally if you end up iterating on a df there is a better / more efficient way to do it as iterating is pretty slow, something like this would be better:

```
df["Result"] = df['Executions'].apply(
    lambda x: sum([int(value['describe']['runtime']) for value in x])
)
```
</blockquote></details>

Thanks, changed to this now.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1030 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j0TezBMbvHZ4Ol0cO:-N67NlpoAYAsJMSorDb2:b-gccjaj) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L1030)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

as before, please be explicit and use `.startswith()`, another advantage is it can handle empty strings:

```
>>> s=''
>>> s.startswith('job-')
False
>>> s[0]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
IndexError: string index out of range
```
</blockquote></details>

Yep, done
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1085 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j0z2oDe7Id3tQ6lSH:-N67hddZ-qoXYGA_ywff:b-vkpuyi) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L1085)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needed?
</blockquote></details>

So I used this to check if the generator returns data or not as I did have an error when it was returning empty generators.
I have changed it to boolean, would this work well?



_Code quote:_
```Python
peek
```
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1092 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j1LC4CdAkw4LihspL:-N67humv8MCKF1GmAgTo:b-vkpuyi) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/DNAnexus_queries.py#L1092)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

these autogenerated and not filled?

also, are you using the returned output? if you're just using it for truth I'd return True / False 
</blockquote></details>

So I used this to check if the generator returns data or not as I did have an error when it was returning empty generators.
I have changed it to boolean, would this work well?
___
*[`Ploutos/scripts/populate_db.py` line 5 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j-vgE9jMs_7zDZM1J:-N5pJsknAHYZ4uHM1pa6:b-gldfdb) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/populate_db.py#L5)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

guessing this isn't intentional import?
</blockquote></details>

Nope, I have removed it.
___
*[`Ploutos/scripts/populate_db.py` line 128 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j3-h99BS3Dy15vOt_:-N67Nq7H17SleDV5mf9D:by4p6d8) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/populate_db.py#L128)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

this returns 2 objects, specifying one returns in a tuple. It would be better to reference both:

```
today_date, day_count = queries.no_of_days_in_month()
```

if you don't need a variable that is returned it is standard to do this to signify it isn't used:

```
today_date, _ = queries.no_of_days_in_month()
```
</blockquote></details>

Yeah I have updated this now.
___
*[`Ploutos/scripts/populate_db.py` line 155 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N5j3ZNi-Lc0fhjpe_PC:-N68bmli6C-BWPamr8nZ:b2nhswv) ([raw file](https://github.com/eastgenomics/ploutos/blob/33d7eb5627eceafcf1de26233573c7327141556e/Ploutos/scripts/populate_db.py#L155)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

will come back to this in next PR
</blockquote></details>

Yep

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @rklocke)

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6)* status: 3 of 4 files reviewed, 1 unresolved discussion (waiting on @rklocke)

**Review by rklocke — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6#-:-N6HhKbt59oGYTP2SaGZ:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @RSWilson1)

___
*[`Ploutos/dashboard/models.py` line 32 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/6#-N67g2g3Aa_7iVIhIpuk:-N6Hh9VG6-5j67hUP-Em:b-f2a3lm) ([raw file](https://github.com/eastgenomics/ploutos/blob/d537c2ef6d30ff2cc6bda7dffafdb78ebff8e78b/Ploutos/dashboard/models.py#L32)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

is this a question for me or @rklocke ?
</blockquote></details>

Happy to change it, the docs say they are basically the same https://docs.djangoproject.com/en/dev/ref/models/fields/#onetoonefield

**Review by RSWilson1 — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6#-:-N6Hpq6k5EFmUkewQBa7:bnfp4nl)* status: 3 of 4 files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/6)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @RSWilson1)

**Pull request merged**
