### PR TITLE
Dockerfile, Docker Compose, subfolder fix

### LINKED ISSUE #19: Float type error
```
env) jason@jason-ThinkPad-T14-Gen-2i:~/github/Ploutos$ python Ploutos/manage.py runscript populate_db
2022-11-02 16:22:23
DNAnexus login successful
There are 11 projects with
no files so they weren't added to the df
15 projects are no longer in the table as they only contained duplicate files
/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py:619: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  aggregated_file_type_all_projs = states_filled_in.append(
/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py:619: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  aggregated_file_type_all_projs = states_filled_in.append(
/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py:619: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  aggregated_file_type_all_projs = states_filled_in.append(
Exception while running run() in 'scripts.populate_db'
Traceback (most recent call last):
  File "Ploutos/manage.py", line 22, in <module>
    main()
  File "Ploutos/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/email_notifications.py", line 65, in run_from_argv
    super().run_from_argv(argv)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/email_notifications.py", line 77, in execute
    super().execute(*args, **options)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/utils.py", line 62, in inner
    ret = func(self, *args, **kwargs)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/commands/runscript.py", line 283, in handle
    run_script(script_mod, *script_args)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/django_extensions/management/commands/runscript.py", line 161, in run_script
    exit_code = mod.run(*script_args)
  File "/home/jason/github/Ploutos/Ploutos/scripts/populate_db.py", line 322, in run
    final_dict, file_type_df = queries.orchestrate_get_files(
  File "/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py", line 1612, in orchestrate_get_files
    unique_sum_df = calculate_totals(unique_grouped_df, 'unique')
  File "/home/jason/github/Ploutos/Ploutos/scripts/DNAnexus_queries.py", line 793, in calculate_totals
    (my_grouped_df['size'] / (2**30) * settings.LIVE_STORAGE_COST_MONTH / days_in_month),
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/ops/common.py", line 70, in new_method
    return method(self, other)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/arraylike.py", line 116, in __mul__
    return self._arith_method(other, operator.mul)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/series.py", line 5639, in _arith_method
    return base.IndexOpsMixin._arith_method(self, other, op)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/base.py", line 1295, in _arith_method
    result = ops.arithmetic_op(lvalues, rvalues, op)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 222, in arithmetic_op
    res_values = _na_arithmetic_op(left, right, op)
  File "/home/jason/github/Ploutos/env/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 163, in _na_arithmetic_op
    result = func(left, right)
numpy.core._exceptions.UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('float64'), dtype('<U6')) -> None
```
Error when running `python manage.py runscript populate_db`. Log above.

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- added Dockerfile, docker-compose.yml
- edited env in `settings.py` to fetch from Docker environment
- changed logging pathway
- edited database in `settings.py` to use Docker container
- edited directory pathway for subfolder hosting e.g. /ploutos
- shaved `requirements.txt`

# Fix
#19

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)

### CODE REVIEW

**Review by rklocke — CHANGES_REQUESTED** [review]
> Reviewed 13 of 13 files at r1.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: all files reviewed (commit messages unreviewed), 1 unresolved discussion (waiting on @JasonLing95, @jethror1, and @RSWilson1)

___
*[`Ploutos/Ploutos/settings.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxMV2F4N772-R2_hQg:-NFxMV2G2pq7sE6tq6H3:b948vqm) ([raw file](https://github.com/eastgenomics/ploutos/blob/eb0cc3aa8d40869c628db84a0f09ca92f67a0d9a/Ploutos/Ploutos/settings.py#L45)):*
> ```Python
>     print(e)
> 
> PROJ_COLOUR_DICT = {
> ```

I have these as below, it may not be clear enough in the README - they were originally in the credentials.json so that if other GLHs were to use it they could change according to how their DNAnexus projects are named / organised and which assays they want to look at. 

I think these would need to be updated as could potentially cause an issue?



_Code snippet:_
```Python
    "PROJ_COLOUR_DICT": {
        "001": "rgb(228,26,28)",
        "002": "rgb(55,126,184)",
        "003": "rgb(77,175,74)",
        "004": "rgb(152,78,163)"
    },
    "ASSAY_COLOUR_DICT": {
        "CEN": "rgb(127, 60, 141)",
        "MYE": "rgb(17, 165, 121)",
        "TWE": "rgb(57, 105, 172)",
        "TSO500": "rgb(242, 183, 1)",
        "SNP": "rgb(231, 63, 116)",
        "CP": "rgb(128, 186, 90)",
        "WES": "rgb(230, 131, 16)",
        "FH": "rgb(0, 134, 149)"
    }
```

**Review by rklocke — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: all files reviewed, 1 unresolved discussion (waiting on @JasonLing95, @jethror1, and @RSWilson1)

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 3 of 13 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: all files reviewed, 5 unresolved discussions (waiting on @JasonLing95 and @RSWilson1)

___
*[`docker-compose.yml` line 7 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyHqr5pe2expdGBjH:-NFxyHqr5pe2expdGBjI:b-58so6z) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/docker-compose.yml#L7)):*
> ```YAML
>     image: mysql:8
>     # ports:
>     #   - "3307:3306"
> ```

needed?



_Code quote:_
```YAML
    # ports:
    #   - "3307:3306"
```
___
*[`docker-compose.yml` line 11 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyLji5e49pC0uucy5:-NFxyLji5e49pC0uucy6:b40da62) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/docker-compose.yml#L11)):*
> ```YAML
>       - 3306
>     env_file:
>       - /home/jason/github/Ploutos/.env
> ```

should this be like this for the server?



_Code quote:_
```YAML
 /home/jason/github/Ploutos/.env
```
___
*[`docker-compose.yml` line 19 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyQLq3220FbXei2-V:-NFxyQLr9Y8w13koUtZw:b-58so6z) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/docker-compose.yml#L19)):*
> ```YAML
>     build: .
>     command: python Ploutos/manage.py runserver 0.0.0.0:8001
>     # ports:
> ```

needed?



_Code quote:_
```YAML
    # ports:
    #   - "8001:8001"
```
___
*[`Ploutos/Ploutos/settings.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyhQl5N0sbfPo1b0q:-NFxyhQl5N0sbfPo1b0r:b-p2glu) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/Ploutos/Ploutos/settings.py#L71)):*
> ```Python
> # See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/
> 
> # SECURITY WARNING: don't run with debug turned on in production!
> ```

can this be in the config please



_Code quote:_
```Python
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: all files reviewed, 5 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`docker-compose.yml` line 7 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyHqr5pe2expdGBjH:-NG1EqlA1OeVs4kKHB06:br1dyvs) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/docker-compose.yml#L7)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

for local debugging it might be useful
___
*[`docker-compose.yml` line 11 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyLji5e49pC0uucy5:-NG1Ven-5_KClrQ_nyO6:b-m10xut) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/docker-compose.yml#L11)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be like this for the server?
</blockquote></details>

different but this is just an example. The real directory will be in release doc
___
*[`docker-compose.yml` line 19 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyQLq3220FbXei2-V:-NG1VH6O4FeapTSOe3Xx:bs5wrt0) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/docker-compose.yml#L19)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

needed?
</blockquote></details>

yes for local debugging
___
*[`Ploutos/Ploutos/settings.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxMV2F4N772-R2_hQg:-NG1VJGL1VMT2vtNAQSf:b-677rqa) ([raw file](https://github.com/eastgenomics/ploutos/blob/eb0cc3aa8d40869c628db84a0f09ca92f67a0d9a/Ploutos/Ploutos/settings.py#L45)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

I have these as below, it may not be clear enough in the README - they were originally in the credentials.json so that if other GLHs were to use it they could change according to how their DNAnexus projects are named / organised and which assays they want to look at. 

I think these would need to be updated as could potentially cause an issue?
</blockquote></details>

added in settings.py
___
*[`Ploutos/Ploutos/settings.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyhQl5N0sbfPo1b0q:-NG1VM-7CFuTbvXnYbF0:b-7tfmjp) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/Ploutos/Ploutos/settings.py#L71)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

can this be in the config please
</blockquote></details>

added

**Review by jethror1 — COMMENTED** [review]
> Reviewed 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: 12 of 13 files reviewed, 1 unresolved discussion (waiting on @rklocke and @RSWilson1)

___
*[`Ploutos/Ploutos/settings.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxMV2F4N772-R2_hQg:-NG29oEwCn5Ux5ZOqxrO:b-tnge4v) ([raw file](https://github.com/eastgenomics/ploutos/blob/eb0cc3aa8d40869c628db84a0f09ca92f67a0d9a/Ploutos/Ploutos/settings.py#L45)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

added in settings.py
</blockquote></details>

@rklocke were you wanting to keep these in the config and import into settings instead of having them hard coded here?
___
*[`Ploutos/Ploutos/settings.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyhQl5N0sbfPo1b0q:-NG2A-r1AtFvO3PXkWvf:bgij9xb) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/Ploutos/Ploutos/settings.py#L71)):*
<details><summary><i>Previously, JasonLing95 (Jason) wrote…</i></summary><blockquote>

added
</blockquote></details>

is this added to the readme as required to be in the config / end file?

**Review by jethror1 — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: all files reviewed, 2 unresolved discussions (waiting on @JasonLing95)

___
*[`Ploutos/dashboard/templates/dashboard/base.html` line 38 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NGGq2v99wV5z3sWkQO2:-NGQzzmT1sNNsbUo3Yk0:b-4uzs2u) ([raw file](https://github.com/eastgenomics/ploutos/blob/6e9623a141ea8a58b5f97edc0a50cd0cfb2f90a9/Ploutos/dashboard/templates/dashboard/base.html#L38)):*
<details><summary><i>Previously, RSWilson1 (Robert Wilson) wrote…</i></summary><blockquote>

@jasonling95 Were the CDNs going to be removed and used locally instead?
</blockquote></details>

CDNs are fine I think if nothing is being done server side and the 10.2 versions work

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: 11 of 20 files reviewed, 2 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/templates/dashboard/base.html` line 38 at r3](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NGGq2v99wV5z3sWkQO2:-NGRXm1J9rtvt54Qv7xx:b-1saauc) ([raw file](https://github.com/eastgenomics/ploutos/blob/6e9623a141ea8a58b5f97edc0a50cd0cfb2f90a9/Ploutos/dashboard/templates/dashboard/base.html#L38)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

CDNs are fine I think if nothing is being done server side and the 10.2 versions work
</blockquote></details>

changed highchart.js to be used locally instead of CDN. Re-deployed on dev server
___
*[`Ploutos/Ploutos/settings.py` line 45 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxMV2F4N772-R2_hQg:-NGICcs041GHXWWWLgE8:bd7be09) ([raw file](https://github.com/eastgenomics/ploutos/blob/eb0cc3aa8d40869c628db84a0f09ca92f67a0d9a/Ploutos/Ploutos/settings.py#L45)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

ideally yes if possible please :)
</blockquote></details>

added env in config file which means we can change it but require restarting the container if we ever change the env
___
*[`Ploutos/Ploutos/settings.py` line 71 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/20#-NFxyhQl5N0sbfPo1b0q:-NGIClhd7lkC0iFneWiW:blt3ole) ([raw file](https://github.com/eastgenomics/ploutos/blob/c903675507a9982b4612a18cef3b673e66189211/Ploutos/Ploutos/settings.py#L71)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

is this added to the readme as required to be in the config / end file?
</blockquote></details>

edited readme to include all envs

**Review by jethror1 — APPROVED** [review]
> Reviewed 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: all files reviewed, 2 unresolved discussions (waiting on @rklocke)

**Review by RSWilson1 — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20#-:-NGRkx3r0pB9CBSLBX2M:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Review by RSWilson1 — APPROVED** [review]
> Reviewed 1 of 2 files at r4, 2 of 4 files at r5, 9 of 9 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/20)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JasonLing95)

**Pull request merged**
