### PR TITLE
fix initial setup and col header

### LINKED ISSUE #11: Error when running for first time if database hasn't been populated.
Error details:

Error from Forms when no data in the database, noticed from DateForm.

How to replicate:
Fresh install, run python manage.py runserver
Error output
AttributeError: 'NoneType' object has no attribute 'date'

This can be solved by populating the db, with `python runscript -v2 populate_db`

### PR DESCRIPTION
**Pull request by JasonLing95**
# Changes
- only query DB on init in `forms.py`
- added css to fix col header sizing

# Fix
#11 #24

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/33)

### CODE REVIEW

**Comment by JasonLing95** [comment]
Currently deployed on dev

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/33)* status: 1 of 13 files reviewed, 3 unresolved discussions (waiting on @jethror1, @rklocke, and @RSWilson1)

___
*[`Ploutos/dashboard/forms.py` line 142 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/33#-NHUeMqiEPxHZ4TXlwlQ:-NHUkXli4tB3okZKwyo5:b-k78rns) ([raw file](https://github.com/eastgenomics/ploutos/blob/dca9d6cac2d21fbc7849ca8f66891405ef3cbb98/Ploutos/dashboard/forms.py#L142)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

why is this date hard coded?
</blockquote></details>

changed to not showing first date if there's no date in DB - makes more sense
___
*[`Ploutos/dashboard/forms.py` line 173 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/33#-NHUeQ8NBumkop5nWn_O:-NHUkg2uETcvtJCnI21T:b-kfu3fe) ([raw file](https://github.com/eastgenomics/ploutos/blob/dca9d6cac2d21fbc7849ca8f66891405ef3cbb98/Ploutos/dashboard/forms.py#L173)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

commented code?
</blockquote></details>

deleted. 
___
*[`Ploutos/dashboard/templates/dashboard/storage.html` line 6 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/33#-NHUeDeYCRVcWOYjki6S:-NHUoDKMExdhd_2aVrpp:bt0pjq1) ([raw file](https://github.com/eastgenomics/ploutos/blob/dca9d6cac2d21fbc7849ca8f66891405ef3cbb98/Ploutos/dashboard/templates/dashboard/storage.html#L6)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

should this be in the css or base template if it is used everywhere?
</blockquote></details>

moved to css in static

**Comment by JasonLing95** [comment]
deployed again on dev

**Review by jethror1 — APPROVED** [review]
> Reviewed 5 of 12 files at r1, 6 of 7 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/33)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke and @RSWilson1)

**Pull request merged**
