### PR TITLE
Plotting into dev

### PR DESCRIPTION
**Pull request by rklocke**
**Small changes:**

- Fixed issue where if there is no entry for the current month, the previous month wouldn't show on the Running Totals monthly plot
- Added cron job for populate_db to django-crontab
- Changed font for the Ploutos navbar brand :)
- Updated README (to be completed when everything merged so can add screenshots)
- Updated requirements.txt
- Formatting of dnanexus_queries.py

image

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/9)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 6 of 12 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/9)* status: 6 of 12 files reviewed, 4 unresolved discussions (waiting on @jethror1 and @rklocke)

___
*[`Ploutos/scripts/DNAnexus_queries.py` line 618 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8FQ74xpsp9J9ajV0:-N8O8FQ83xXAz5AujNfy:b-58so6z) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/DNAnexus_queries.py#L618)):*
> ```Python
>     empty_proj_df = pd.DataFrame([empty_project_rows])
>     # Add the rows to the df for those projects
>     # aggregated_file_type_all_projs = pd.concat(
> ```

needed?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 888 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8KfG8R1v10Um-_xr:-N8O8KfG8R1v10Um-_xs:b-58so6z) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/DNAnexus_queries.py#L888)):*
> ```Python
> 
>     # # Append the projects with no files to the final merged dataframe
>     # empty_proj_df = pd.DataFrame([empty_project_rows])
> ```

needed?
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1272 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8WCXBYIO3f6tsmCT:-N8O8WCXBYIO3f6tsmCU:b-58so6z) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/DNAnexus_queries.py#L1272)):*
> ```Python
>                             )
>                         else:
>                             # states = subjob['describe']['stateTransitions']
> ```

needed?
___
*[`Ploutos/scripts/file_plots.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8bTYA0qs0F4yCNSJ:-N8O8bTYA0qs0F4yCNSK:b12eubs) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/file_plots.py#L22)):*
> ```Python
>         self.assay_colours = sp.StoragePlotFunctions(
>         ).assay_colours.copy()
>         self.my_chart_data = sp.StoragePlotFunctions().chart_data.copy()
> ```

I assume this is used elsewhere?

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/9)* status: 6 of 12 files reviewed, 4 unresolved discussions (waiting on @jethror1)

___
*[`Ploutos/scripts/DNAnexus_queries.py` line 618 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8FQ74xpsp9J9ajV0:-N8O9GZL9hZeLIsBhcIy:bmfmk7w) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/DNAnexus_queries.py#L618)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done. (was trying to change to concat from append but it broke things)
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 888 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8KfG8R1v10Um-_xr:-N8O9XJq1F8OEZsYBfdj:b-896fix) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/DNAnexus_queries.py#L888)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needed?
</blockquote></details>

Done.
___
*[`Ploutos/scripts/DNAnexus_queries.py` line 1272 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8WCXBYIO3f6tsmCT:-N8O9aZaBx_1-nn-ctDU:bke0ggd) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/DNAnexus_queries.py#L1272)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

needed?
</blockquote></details>

this was Rob's so not sure sorry, I was just updating formatting
___
*[`Ploutos/scripts/file_plots.py` line 22 at r1](https://reviewable.io/reviews/eastgenomics/ploutos/9#-N8O8bTYA0qs0F4yCNSJ:-N8OA6Zv0GbzGSK3G2gT:bk7j7c5) ([raw file](https://github.com/eastgenomics/ploutos/blob/14fb523d73bdcda8eefb1a3df548399ac032ad20/Ploutos/scripts/file_plots.py#L22)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

I assume this is used elsewhere?
</blockquote></details>

self.my_chart_data is used for all the charts, self.file_type_colours used for both size and count chart functions for file type default charts

**Review by jethror1 — APPROVED** [review]
> Reviewed 5 of 12 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Review by jethror1 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/9)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
