### PR TITLE
Log ins and other minor changes

### PR DESCRIPTION
**Pull request by rklocke**
Main changes:
- Added log in functionality (no charts or tables shown until logged in, then can see data and their username and a log out button is shown in the top right corner). Users logged out after closing a browser or 30 mins of inactivity.
- Changed to POST requests to hide things submitted on form + CSRF token in URL
- Changed favicon to little red circle with P :)
- Added reset button logic for running total chart forms. Note both charts reset when either form reset is submitted - can look at changing this in future.
- Added extra checks for whether data exists for running total charts and changed the charts to show 'No data to display' message rather than weird empty Plotly axes with random numbers.

image
image
image

---
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/8)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 11 of 16 files at r1, 2 of 5 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/8)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @jethror1 and @rklocke)

___
*[`Ploutos/Ploutos/settings.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/8#-N7q4C5I6DNzwejZJZVX:-N7q4C5I6DNzwejZJZVY:bfrlore) ([raw file](https://github.com/eastgenomics/ploutos/blob/6f4b0c61d506be97c9f1595fe5a7c9c3e689220a/Ploutos/Ploutos/settings.py#L82)):*
> ```Python
>         'DIRS': [
>             f'{BASE_DIR}/dashboard/templates/dashboard/',
>             BASE_DIR / "templates"
> ```

when building paths it's safer to use `os.path.join(BASE_DIR, "templates")`, it will handle duplicate and missing leading/trailing slashes



_Code quote:_
```Python
BASE_DIR / "templates"
```
___
*[`Ploutos/Ploutos/settings.py` line 291 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/8#-N7q4vjg0hEZk_gYoo7G:-N7q4vjg0hEZk_gYoo7H:b-8kmyb1) ([raw file](https://github.com/eastgenomics/ploutos/blob/6f4b0c61d506be97c9f1595fe5a7c9c3e689220a/Ploutos/Ploutos/settings.py#L291)):*
> ```Python
> # Also log user out after half an hour of inactivity
> SESSION_EXPIRE_AT_BROWSER_CLOSE = True
> SESSION_COOKIE_AGE = 30 * 60
> ```

1800?
___
*[`Ploutos/scripts/populate_db.py` line 287 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/8#-N7q545e73laeOLGrGrZ:-N7q545e73laeOLGrGr_:b-1e9maq) ([raw file](https://github.com/eastgenomics/ploutos/blob/6f4b0c61d506be97c9f1595fe5a7c9c3e689220a/Ploutos/scripts/populate_db.py#L287)):*
> ```Python
>     populate_database_files(final_dict)
>     populate_file_types(file_type_df)
>     # executions_df = queries.orchestrate_get_executions(proj_list)
> ```

commented code needed?

**Review by rklocke — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/8)* status: 13 of 16 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`Ploutos/Ploutos/settings.py` line 82 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/8#-N7q4C5I6DNzwejZJZVX:-N7q5qPWBzLOLWLMH-sW:bjpu14n) ([raw file](https://github.com/eastgenomics/ploutos/blob/6f4b0c61d506be97c9f1595fe5a7c9c3e689220a/Ploutos/Ploutos/settings.py#L82)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

when building paths it's safer to use `os.path.join(BASE_DIR, "templates")`, it will handle duplicate and missing leading/trailing slashes
</blockquote></details>

Only did this as Django settings itself says "# Build paths inside the project like this: BASE_DIR / 'subdir'." but have changed :) also realised somehow logging was in settings twice so pls ignore the delete
___
*[`Ploutos/Ploutos/settings.py` line 291 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/8#-N7q4vjg0hEZk_gYoo7G:-N7q6gjd-sb_P24tqniU:b-rnj40w) ([raw file](https://github.com/eastgenomics/ploutos/blob/6f4b0c61d506be97c9f1595fe5a7c9c3e689220a/Ploutos/Ploutos/settings.py#L291)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

1800?
</blockquote></details>

Wrote as others had online so easier to understand in terms of minutes but have changed to 1800
___
*[`Ploutos/scripts/populate_db.py` line 287 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/8#-N7q545e73laeOLGrGrZ:-N7q73DTCsuctplsEv48:bj2ki96) ([raw file](https://github.com/eastgenomics/ploutos/blob/6f4b0c61d506be97c9f1595fe5a7c9c3e689220a/Ploutos/scripts/populate_db.py#L287)):*
<details><summary><i>Previously, jethror1 wrote…</i></summary><blockquote>

commented code needed?
</blockquote></details>

Oops uncommented, thanks

**Review by jethror1 — CHANGES_REQUESTED** [review]
> Reviewed 1 of 5 files at r2, 1 of 2 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/8)* status: 15 of 16 files reviewed, 1 unresolved discussion (waiting on @jethror1 and @rklocke)

___
*[`Ploutos/Ploutos/settings.py` line 291 at r2](https://reviewable.io/reviews/eastgenomics/ploutos/8#-N7q4vjg0hEZk_gYoo7G:-N7q82vV7rQ9a9jB7GiY:b-gwrfzd) ([raw file](https://github.com/eastgenomics/ploutos/blob/6f4b0c61d506be97c9f1595fe5a7c9c3e689220a/Ploutos/Ploutos/settings.py#L291)):*
<details><summary><i>Previously, rklocke (Rebecca Locke) wrote…</i></summary><blockquote>

Wrote as others had online so easier to understand in terms of minutes but have changed to 1800
</blockquote></details>

ahhh okay, makes sense

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/ploutos/8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @rklocke)

**Pull request merged**
