### PR TITLE
Update to Running Total Page (Minify and Clean Up View.py)

### PR DESCRIPTION
**Pull request by JasonLing95**
- added debug toolbar which only shows when `DEBUG` is True
- added a cache container in `docker-compose.yml`
- clean up view.py for index page (Running Org Total)
- Previously data sent from backend to frontend was 7.5MB, now 1.5MB
- Added compression for JS files in base.html (smaller size) which translate to faster loading (1s to 500ms)

Screenshot from 2023-03-13 16-24-20

- - -
This change is [Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/51)

### CODE REVIEW

**Review by jethror1 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/51)* status: 0 of 23 files reviewed, 3 unresolved discussions (waiting on @JasonLing95)

___
*[`Ploutos/dashboard/forms.py` line 103 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/51#-NQVdaiW6SqlCnVD_dwP:-NQVdaiW6SqlCnVD_dwQ:b-jccjea) ([raw file](https://github.com/eastgenomics/Ploutos/blob/14a749ce8af0ada04d9841d6293f450bd4c431d4/Ploutos/dashboard/forms.py#L103)):*
> ```Python
> 
>         # Check both dates are entered
>         if (start is None) and (end is None):
> ```

I think its better to do `if not start and not end` unless you need to explicitly check for it being None?



_Code quote:_
```Python
if (start is None) and (end is None):
```
___
*[`Ploutos/dashboard/forms.py` line 105 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/51#-NQVdjc8Eaw6lItk0f1L:-NQVdjc8Eaw6lItk0f1M:b-fwamu3) ([raw file](https://github.com/eastgenomics/Ploutos/blob/14a749ce8af0ada04d9841d6293f450bd4c431d4/Ploutos/dashboard/forms.py#L105)):*
> ```Python
>         if (start is None) and (end is None):
>             self.add_error(None, error="Please enter dates")
>         if start and (end is None):
> ```

`if start and not end:`



_Code quote:_
```Python
f start and (end is None)
```
___
*[`Ploutos/dashboard/forms.py` line 110 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/51#-NQVdnsF5Plr6b53z_Q1:-NQVdnsF5Plr6b53z_Q2:bda8ylh) ([raw file](https://github.com/eastgenomics/Ploutos/blob/14a749ce8af0ada04d9841d6293f450bd4c431d4/Ploutos/dashboard/forms.py#L110)):*
> ```Python
>             )
> 
>         if end and (start is None):
> ```

`if end and not start:`



_Code quote:_
```Python
if end and (start is None):
```

**Review by JasonLing95 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/51)* status: 0 of 23 files reviewed, 3 unresolved discussions (waiting on @jethror1)

___
*[`Ploutos/dashboard/forms.py` line 103 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/51#-NQVdaiW6SqlCnVD_dwP:-NQWV3Ym7Xpeho8kwxA2:b-n9tkhd) ([raw file](https://github.com/eastgenomics/Ploutos/blob/14a749ce8af0ada04d9841d6293f450bd4c431d4/Ploutos/dashboard/forms.py#L103)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

I think its better to do `if not start and not end` unless you need to explicitly check for it being None?
</blockquote></details>

changed
___
*[`Ploutos/dashboard/forms.py` line 105 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/51#-NQVdjc8Eaw6lItk0f1L:-NQWV4Dz5QKCFVr6jn0R:b-n9tkhd) ([raw file](https://github.com/eastgenomics/Ploutos/blob/14a749ce8af0ada04d9841d6293f450bd4c431d4/Ploutos/dashboard/forms.py#L105)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if start and not end:`
</blockquote></details>

changed
___
*[`Ploutos/dashboard/forms.py` line 110 at r1](https://reviewable.io/reviews/eastgenomics/Ploutos/51#-NQVdnsF5Plr6b53z_Q1:-NQWV4o0DabkEMGxNu9D:b-n9tkhd) ([raw file](https://github.com/eastgenomics/Ploutos/blob/14a749ce8af0ada04d9841d6293f450bd4c431d4/Ploutos/dashboard/forms.py#L110)):*
<details><summary><i>Previously, jethror1 (Jethro Rainford) wrote…</i></summary><blockquote>

`if end and not start:`
</blockquote></details>

changed

**Comment by JasonLing95** [comment]
app for this pr version is now on dev

**Review by jethror1 — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/eastgenomics/Ploutos/51)* status: 1 of 25 files reviewed, all discussions resolved

**Pull request merged**
